
start: Main.class Broker.class Computador.class Conector.class Connection.class Mensaje.class Pais.class Utils.class
	java Main

# %: %.class
	# @echo $<

%.class: %.java
	javac $<

clean:
	rm *.class
